//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba9Dic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sitios()
        {
            this.Informantes = new HashSet<Informantes>();
            this.Testigos = new HashSet<Testigos>();
            this.Victimas = new HashSet<Victimas>();
        }
    
        public int Id_Sitio { get; set; }
        public string CodigoSitio { get; set; }
        public string Coord_X { get; set; }
        public string Coord_Y { get; set; }
        public Nullable<decimal> Altitud { get; set; }
        public Nullable<int> Propiedad { get; set; }
        public string Antecedentes { get; set; }
        public string RelatoAcontecimientos { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public Nullable<System.DateTime> FechaInhumacion { get; set; }
        public Nullable<decimal> NumeroVictimas { get; set; }
        public Nullable<bool> ExhumacionAnterior { get; set; }
        public Nullable<bool> MaterialesAdicionales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informantes> Informantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testigos> Testigos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Victimas> Victimas { get; set; }
    }
}
